name: Docker Build Backend App

on:
  push:
    branches:
      - master
    paths:
      - 'backend/*'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TOKEN: ${{ secrets.GITHUB_TOKEN_GROUP_4 }}
      HASH: $GITHUB_SHA
      REGISTRY: docker.pkg.github.com
      IMAGE: OAMKpathfinder/group4/backend
      USER: arpadgabor
      PATH: backend

    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - name: Login to Registry
      run: docker login $REGISTRY -u $USER -p $TOKEN
    - name: Build image
      run: cd $PATH && docker build -t "${REGISTRY}/${IMAGE}:latest" -t "${REGISTRY}/${IMAGE}:${HASH}" .
    - name: Push to Docker Hub
      run: docker push $REGISTRY/$IMAGE:latest && docker push $REGISTRY/$IMAGE:$HASH