name: 'Docker Build Backend App'
on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@master
      with:
        fetch-depth: 1

    - name: Login to Registry
      run: docker login $REGISTRY -u $USER -p $TOKEN
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REGISTRY: docker.pkg.github.com
        USER: arpadgabor

    - name: Build image
      run: cd $PATH && docker build -t "$REGISTRY/$IMAGE:latest" -t "$REGISTRY/$IMAGE:$HASH" .
      env:
        HASH: $GITHUB_SHA
        REGISTRY: docker.pkg.github.com
        IMAGE: OAMKpathfinder/group4/backend
        PATH: backend

    - name: Push to Docker Hub
      run: docker push $REGISTRY/$IMAGE:latest && docker push $REGISTRY/$IMAGE:$HASH
      env:
        HASH: $GITHUB_SHA
        REGISTRY: docker.pkg.github.com
        IMAGE: OAMKpathfinder/group4/backend