name: 'Docker Build Backend App'
on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@master
      with:
        fetch-depth: 1

    - name: Login to Registry
      run: docker login $REGISTRY -u $USER -p $TOKEN
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REGISTRY: docker.pkg.github.com
        USER: arpadgabor

    - name: Build image
      run: docker build . -t "$REGISTRY/$IMAGE:latest" --verbose
      env:
        REGISTRY: docker.pkg.github.com
        IMAGE: oamkpathfinder/group4/backend

    - name: Push to Registry
      run: docker push "$REGISTRY/$IMAGE:latest" && docker push "$REGISTRY/$IMAGE:$GITHUB_SHA"
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REGISTRY: docker.pkg.github.com
        IMAGE: oamkpathfinder/group4/backend